sudo: required
services:
  - docker

before_install: 
  - docker build -t mgarcia11/docker-react -f Dockerfile.dev .
  - docker run 

script:
  - docker run -e CI=true mgarcia11/docker-react npm run test -- --coverage